
include .Renviron
include .env

check-env:
	@echo "GOOGLE_SERVICE_ACC=${GOOGLE_SERVICE_ACC}"
	@echo "GDOCS_SCREENSHOTS_UID=${GDOCS_SCREENSHOTS_UID}"
	@echo "GDOCS_ANNOTATIONS_UID=${GDOCS_ANNOTATIONS_UID}"
	@echo "GOOGLE_AUTH_CLIENT_ID=${GOOGLE_AUTH_CLIENT_ID}"
	@echo "GOOGLE_SERVICE_ACC_JSON=${GOOGLE_SERVICE_ACC_JSON}"

docker-build:
	docker build -t ${DOCKER_REGISTRY}/ShinyImgVoteR:0.0.6 .

docker-run:
	docker run -d -p 8000:8000 \
		-e GOOGLE_SERVICE_ACC=${GOOGLE_SERVICE_ACC} \
		-e GOOGLE_SERVICE_ACC_JSON=${GOOGLE_SERVICE_ACC_JSON} \
		-e GDOCS_SCREENSHOTS_UID=${GDOCS_SCREENSHOTS_UID} \
		-e GDOCS_ANNOTATIONS_UID=${GDOCS_ANNOTATIONS_UID} \
		-e GOOGLE_AUTH_CLIENT_ID=${GOOGLE_AUTH_CLIENT_ID} \
		${DOCKER_REGISTRY}/ShinyImgVoteR:0.0.6

bk-docker-run:
	docker run -d -p 8000:8000 \
		-e GOOGLE_SERVICE_ACC="${GOOGLE_SERVICE_ACC}" \
		-e GDOCS_SCREENSHOTS_UID="${GDOCS_SCREENSHOTS_UID}" \
		-e GDOCS_ANNOTATIONS_UID="${GDOCS_ANNOTATIONS_UID}" \
		-e GOOGLE_AUTH_CLIENT_ID="${GOOGLE_AUTH_CLIENT_ID}" \
		# --volume $(shell pwd)/gsheets_config.json:/srv/shiny-server/gsheets_config.json \
		# --entrypoint /bin/bash \
		ShinyImgVoteR:0.0.6
		# -c "R -e \"install.packages('tidyverse')\" && R -e \"shiny::runApp('/srv/shiny-server/', port=3838, host='0.0.0.0')\""

push-to-docker-registry:
	docker push ${DOCKER_REGISTRY}/ShinyImgVoteR:0.0.6

init-sqlite-db:
	Rscript init_db.R

dev:
	# R -e "renv::restore()" && \
	Rscript run.R

test:
	make -f Makefile.test test

stop:
	fuser -k 8000/tcp

