---
images_dir: "./app_env/images"
user_data_dir: "./app_env/user_data"
server_data_dir: "./app_env/server_data"

to_be_voted_images_file: "./app_env/images/to_be_voted_images.tsv"
grouped_credentials_file: "./app_env/config/institute2userids2password.yaml"
sqlite_file: "./app_env/db.sqlite"
shutdown_trigger_file: "./app_env/config/STOP"

application_title: ShinyImgVoteR (B1MG Somatic Mutation Voting)
radioBtns_label: Please select your assessment [num keys 1-4]
checkboxes_label: Please select the reason(s) [keyboard keys a-f]

radio_options:
  Yes, it is the somatic mutation shown above: 
    value: 'yes'
    db_column: vote_count_correct
    comment_box: true
    max_matching_votes: 1
  No, it is a different somatic mutation:
    value: diff_var
    db_column: vote_count_different_variant
    comment_box: true
    max_matching_votes: 1
  No, it is germline leakage:
    value: germline
    db_column: vote_count_germline
    comment_box: true
    max_matching_votes: 1
  None of the above:
    value: none_of_above
    db_column: vote_count_none_of_above
    comment_box: true
    max_matching_votes: 1

observations_dict:
  Issues with coverage: coverage
  Alignment issues: alignment
  Complex events: complex
  Screenshot is inconclusive: img_inconclusive

observation_hotkeys:
- a
- s
- d
- f
nt2color_map:
  T: "#E31A1C"
  C: "#1F78B4"
  A: "#33A02C"
  G: "#FF7F00"
  "-": black
db_general_cols:
- coordinates
- REF
- ALT
- path
db_query_keys:
- coordinates
- REF
- ALT
user_annotations_colnames:
- coordinates
- REF
- ALT
- agreement
- observation
- comment
- shinyauthr_session_id
- time_till_vote_casted_in_seconds
cookie_expiry: 1
